language: clojure
sudo: false
env:
  global:
  - GH_REF: github.com/clojure-tw/clojure-tw.github.io.git
  - secure: UtQPvGi+xNlcBVJQpTcRHUxlhj43x3tjfLT/d+IKKuipxkbgJttoe/lffG/UyUvjZA6ojBfaqyfHap65aVruVZfLa7lxTsrfeVILe9QHo6p94QBmRX2u5PWdxSPYBNRHVdnb3OxDHRJGsJw8tn9/g3dL1xzrmQIpXSe0VVZKGoB8zdo2G/WWOU9sEiUXldUMbmizQXftiSWmzXyhaXLBspodu8SYS+1aBKm+ZIeLKggw0rN/hB+ITR0CGf8NZXs2/8NtOgFhrN5wy/dpYBrUnvP2u9J32aEI8vl1ACD64MDwgdkM/phlKJ7Ibt/DpzYFQwnJt6Qk0JxkLMmeoib7fCRWFuLA0tk7bHMVKbJz12Mg4aH+4C8+HHgV7pOK27DMyxU6441x28ZM3acjNyPCgBgMACMaCF+Bel7su2++Q2z8AKV3iVZ0EBXEZm/gbmWFCnCk53bnNKWG3sWbugwvmzNSEDwoJ+Mcd1d4YZ2k9OfsNMrd7mNZnpMQ5u5ZH9RfAHDrb+dXGcdsDcjhmeh1clzP/a4VYOlVpXMCLwTYJ/t9oPWePG6LFrevfJaTAIMaRdgOuYGixrMVFocltdpqxjfpbx3bXtXnMcqxfQa/+qPO/UIm3/ujz7X5yOLHEk5FPXcFFBiMOyuSbKO4jrxKqwp+r/Hb/1+TQdDSFSFuWvQ=
jdk:
  - oraclejdk8
install:
  - wget -O boot https://github.com/boot-clj/boot-bin/releases/download/2.4.2/boot.sh
  - chmod 755 boot
  - ./boot -V
script:
  - ./boot prod
  - ./deploy.sh
